# Generated by Django 5.1.1 on 2024-10-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_data_set_id', models.CharField(max_length=100)),
                ('pds_path', models.CharField(max_length=255)),
                ('pds_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='Dremio_info.source')),
            ],
        ),
    ]
